name: clickashoe
favicon: null
layout_spectrum: 0.03313736757263541
typography_spectrum: 0.4223808255046606
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.13230310752987862
  lightness: 0.5205812419299036
  saturation: 0.39143674774095416
  rhythmicContrast: 0.8134337875526398
purpose: []
